version: '2'
services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    container_name: gcb_wordpress_mariadb_data
    image: gcb_wordpress_mariadb_data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
  apache:
    build:
      context: .
      dockerfile: Dockerfile-wordpress
    container_name: gcb_wordpress_apache_data
    image: gcb_wordpress_apache_data
    expose:
      - 9875
    ports:
      - 9875:9875
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb

