---
name: Django test container
author: Didi Hoffmann <didi@green-coding.berlin>
description: Encapsulation of the Django official unit tests for energy measurement

services:
  gcb-django-tests:
    image: gcb_django_tests
    build: .

flow:
  - name: Django test
    container: gcb-django-tests
    commands:
      - type: console
        note: Starting the django tests
        command: bash /tmp/django/tests/runner.sh | awk '/Found [0-9]+ test\(s\)/ { gsub(/Found | test\(s\)/, "", $0); print "GMT_SCI_R=" $0 }'
        shell: bash
        log-stdout: True
        read-sci-stdout: True
