services:
  db:
    image: mariadb:10.6.4-focal
    container_name: green-coding-wordpress-mariadb-data-container
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    volumes:
      - ./wordpress-dump.sql:/docker-entrypoint-initdb.d/wordpress-dump.sql
  wordpress:
    image: wordpress:latest
    container_name: green-coding-wordpress-apache-data-container
    ports:
      - 9875:9875
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
    volumes:
      - ./html:/var/www/wordpress-green-coding
      - ./wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf:ro

