---
name: SCI for idle
author: Arne Tarara <arne@green-coding.berlin>
description: Idle the container for 60 seconds and outputting SCI

sci:
  R_d: minute of idling

services:
  gcb-idle:
    image: alpine
    command: sh

flow:
  - name: Idle
    container: gcb-idle
    commands:
      - type: console
        command: sleep 60
        note: Starting Sleep
      - type: console
        note: Writing SCI to stdout
        command: echo GMT_SCI_R=1
        log-stdout: True
        read-sci-stdout: True
