---
name: Stress Container 10 cores Core 5 Seconds
author: Arne Tarara
version: 1
architecture: linux

services:
  alpine-stress:
    type: container
    image: stress_stress

flow:
  - name: Stress
    container: alpine-stress
    commands:
# Alpine does not have stress, so we use stress-ng
# We need the -q flag because otherwise it will write debug to STDERR
      - type: console
        command: stress-ng -c 10 -t 5 -q
        note: Starting Stress
