services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    container_name: green-coding-mariadb-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile-apache-php
    container_name: green-coding-apache-php-container
    restart: always
    ports:
       - 9875:9875
    volumes:
      - ./wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf:ro
      - ./html:/var/www/html:ro
