services:
  db:
    image: mariadb:10.6.4-focal
    container_name: green-coding-wordpress-mariadb-basic-container
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
  wordpress:
    image: wordpress:latest
    container_name: green-coding-wordpress-apache-basic-container
    ports:
      - 9875:9875
    restart: always
    depends_on:
      - db
    volumes:
      - ./wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf:ro
