---
name: Idle Container for 5 Seconds
author: Arne Tarara
version: 1
architecture: linux

services:
  alpine-idle:
    image: alpine
    cmd: sh

flow:
  - name: Idle
    container: gcb_alpine_idle
    commands:
      - type: console
        command: sleep 5
        note: Starting Sleep
