---
name: Idle Container for 5 Minutes
author: Arne Tarara <arne@green-coding.berlin>
description: Idle the container for 5 seconds

services:
  gcb-idle:
    image: alpine
    cmd: sh

flow:
  - name: Idling for 5 Minutes
    container: gcb-idle
    commands:
      - type: console
        command: sleep 300
        note: Starting Sleep
